export const calculateExpressions = [
    { value: "1", color: "info" },
    { value: "2", color: "info" },
    { value: "3", color: "info" },
    { value: "+", color: "warning" },
    { value: "4", color: "info" },
    { value: "5", color: "info" },
    { value: "6", color: "info" },
    { value: "-", color: "warning" },
    { value: "7", color: "info" },
    { value: "8", color: "info" },
    { value: "9", color: "info" },
    { value: "*", color: "warning" },
    { value: "0", color: "info" },
    { value: ".", color: "warning" },
    { value: "/", color: "warning" },
    { value: "AC", color: "error" },
];
